VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TILE_SIZE = 16

PLAYER_WALK_SPEED = 60

MAP_WIDTH = VIRTUAL_WIDTH / TILE_SIZE - 2
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) - 2

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (MAP_WIDTH * TILE_SIZE)) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - (MAP_HEIGHT * TILE_SIZE)) / 2

MAP_TILE_ROCK = 'R'
MAP_TILE_DIAMOND = 'D'
MAP_TILE_WALL = 'W'
MAP_TILE_EXIT = 'E'
MAP_TILE_GROUND = '-'
MAP_TILE_EMPTY = ' '

TILE_SPEED_BUMP = {
    [MAP_TILE_ROCK] = 0,
    [MAP_TILE_DIAMOND] = 0.7,
    [MAP_TILE_WALL] = 0,
    [MAP_TILE_EXIT] = 1,
    [MAP_TILE_GROUND] = 0.5,
    [MAP_TILE_EMPTY] = 1,
}
